# Copyright (c) 2024 The Regents of the University of Michigan.
# All Rights Reserved. Licensed according to the terms of the Revised
# BSD License. See LICENSE.txt for details.
name: "Build nightly and on push to main"

on:
  push:
    branches: ["main"]
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "mr-smithers-excellent/docker-build-push@v6"
      with:
        image: "kube-debug"
        addLatest: true
        addTimestamp: true
        registry: "ghcr.io"
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
